--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: agency_license_photos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agency_license_photos (
    agency_id bigint NOT NULL,
    license_photo_url character varying(255)
);


--
-- Name: comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comments (
    id bigint NOT NULL,
    content text NOT NULL,
    rating integer NOT NULL,
    role character varying(255) NOT NULL,
    role_id bigint NOT NULL,
    user_id bigint,
    CONSTRAINT comments_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'GUIDE'::character varying, 'HOTEL'::character varying, 'VEHICLE'::character varying])::text[])))
);


--
-- Name: comments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: drivers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.drivers (
    id bigint NOT NULL,
    age integer,
    created_at timestamp(6) without time zone,
    driver_license_number character varying(255),
    driver_license_photo character varying(255),
    experience integer,
    license_expiry_date date,
    agency_id bigint,
    user_id bigint
);


--
-- Name: drivers_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.drivers_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: guid_languages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.guid_languages (
    guid_id bigint NOT NULL,
    language character varying(255)
);


--
-- Name: guid_nic_photos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.guid_nic_photos (
    guid_id bigint NOT NULL,
    nic_photo_front character varying(255)
);


--
-- Name: guid_nic_photos_back; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.guid_nic_photos_back (
    guid_id bigint NOT NULL,
    nic_photo_back character varying(255)
);


--
-- Name: guid_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.guid_requests (
    id bigint NOT NULL,
    status character varying(255),
    guid_id bigint,
    trip_id bigint,
    user_id bigint
);


--
-- Name: guid_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.guid_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.guid_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: guid_slta_license_photos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.guid_slta_license_photos (
    guid_id bigint NOT NULL,
    slta_license_photo character varying(255)
);


--
-- Name: guid_specializations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.guid_specializations (
    guid_id bigint NOT NULL,
    specialization character varying(255)
);


--
-- Name: guides; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.guides (
    id bigint NOT NULL,
    bio character varying(2000),
    created_at timestamp(6) without time zone,
    experience_years integer,
    hours_rate double precision,
    is_available boolean,
    is_verified boolean,
    nic_number character varying(255),
    slta_license_expiry timestamp(6) without time zone,
    slta_license_id character varying(255),
    user_id bigint
);


--
-- Name: guides_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.guides_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: hotel_amenities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.hotel_amenities (
    hotel_id bigint NOT NULL,
    amenity character varying(255)
);


--
-- Name: hotel_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.hotel_images (
    hotel_id bigint NOT NULL,
    image_url character varying(255)
);


--
-- Name: hotel_license_photos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.hotel_license_photos (
    hotel_id bigint NOT NULL,
    license_photo_url character varying(255)
);


--
-- Name: hotels; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.hotels (
    id bigint NOT NULL,
    city character varying(255),
    created_at timestamp(6) without time zone,
    description character varying(2000),
    district character varying(255),
    hotel_name character varying(255),
    is_verified boolean,
    province character varying(255),
    registration_no character varying(255),
    street character varying(255),
    type character varying(255),
    user_id bigint
);


--
-- Name: hotels_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.hotels_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: profile_pictures; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profile_pictures (
    user_id bigint NOT NULL,
    profile_picture character varying(255)
);


--
-- Name: room_amenities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.room_amenities (
    room_id bigint NOT NULL,
    amenity character varying(255)
);


--
-- Name: room_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.room_images (
    room_id bigint NOT NULL,
    image_url character varying(255)
);


--
-- Name: rooms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rooms (
    id bigint NOT NULL,
    availability boolean,
    bed_types character varying(255),
    created_at timestamp(6) without time zone,
    description character varying(255),
    max_guests character varying(255),
    price_per_night double precision,
    room_type character varying(255),
    hotel_id bigint NOT NULL
);


--
-- Name: rooms_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.rooms_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: trip_interests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trip_interests (
    trip_id bigint NOT NULL,
    interest character varying(255)
);


--
-- Name: trip_places; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trip_places (
    trip_id bigint NOT NULL,
    place_id bigint
);


--
-- Name: trip_selected_guides; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trip_selected_guides (
    trip_id bigint NOT NULL,
    guide_id bigint
);


--
-- Name: trip_selected_hotels; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trip_selected_hotels (
    trip_id bigint NOT NULL,
    hotel_id bigint NOT NULL
);


--
-- Name: trip_selected_night_hotels; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trip_selected_night_hotels (
    trip_id bigint NOT NULL,
    night_hotel_id bigint
);


--
-- Name: trip_selected_night_rooms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trip_selected_night_rooms (
    trip_id bigint NOT NULL,
    night_room_id bigint
);


--
-- Name: trip_selected_rooms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trip_selected_rooms (
    trip_id bigint NOT NULL,
    room_id bigint NOT NULL
);


--
-- Name: trips; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trips (
    id bigint NOT NULL,
    accommodation_preference character varying(255),
    activity_level character varying(255),
    age_group character varying(255),
    agreed_to_terms boolean,
    base_price numeric(10,2),
    booking_summary_json text,
    budget_range character varying(255),
    country character varying(255),
    destination character varying(255),
    dining_preference character varying(255),
    distance_km integer,
    duration character varying(255),
    email character varying(255),
    estimate_duration character varying(255),
    full_name character varying(255),
    group_type character varying(255),
    itinerary text,
    nic_number character varying(255),
    number_of_adults integer,
    number_of_kids integer,
    occupation character varying(255),
    optional_contact character varying(255),
    phone character varying(255),
    pickup_location character varying(255),
    referral_source character varying(255),
    special_requests character varying(255),
    start_time time(6) without time zone,
    total_fare numeric(10,2),
    tour_preferences_json text,
    travel_details_json text,
    travel_experience character varying(255),
    travel_style character varying(255),
    trip_code character varying(255),
    trip_end_date date,
    trip_start_date date,
    trip_status character varying(255),
    guides bigint,
    selected_vehicle bigint,
    selected_vehicle_agency bigint,
    user_id bigint,
    CONSTRAINT trips_trip_status_check CHECK (((trip_status)::text = ANY ((ARRAY['pending'::character varying, 'accepted'::character varying, 'ongoing'::character varying, 'completed'::character varying, 'cancelled'::character varying])::text[])))
);


--
-- Name: trips_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.trips_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    doc_id character varying(255),
    email character varying(255),
    first_name character varying(255),
    is_deleted boolean DEFAULT false,
    last_name character varying(255),
    role character varying(255)
);


--
-- Name: users_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.users_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: vehicle_agencies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vehicle_agencies (
    id bigint NOT NULL,
    agency_name character varying(255),
    city character varying(255),
    created_at timestamp(6) without time zone,
    description character varying(2000),
    district character varying(255),
    province character varying(255),
    registration_no character varying(255),
    street character varying(255),
    user_id bigint
);


--
-- Name: vehicle_agencies_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.vehicle_agencies_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: vehicle_amenities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vehicle_amenities (
    vehicle_id bigint NOT NULL,
    amenity character varying(255)
);


--
-- Name: vehicle_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vehicle_images (
    vehicle_id bigint NOT NULL,
    image_url character varying(255)
);


--
-- Name: vehicles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vehicles (
    id bigint NOT NULL,
    availability boolean,
    base_price numeric(38,2),
    capacity integer,
    created_at timestamp(6) without time zone,
    insurance_expiry_date date,
    insurance_number character varying(255),
    is_verified boolean,
    price_per_kilometer character varying(255),
    registration_no character varying(255),
    vehicle_model character varying(255),
    vehicle_no character varying(255),
    vehicle_type character varying(255),
    agency_id bigint
);


--
-- Name: vehicles_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.vehicles_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Data for Name: agency_license_photos; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.agency_license_photos (agency_id, license_photo_url) FROM stdin;
\.


--
-- Data for Name: comments; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.comments (id, content, rating, role, role_id, user_id) FROM stdin;
\.


--
-- Data for Name: drivers; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.drivers (id, age, created_at, driver_license_number, driver_license_photo, experience, license_expiry_date, agency_id, user_id) FROM stdin;
\.


--
-- Data for Name: guid_languages; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.guid_languages (guid_id, language) FROM stdin;
1	English
1	Sinhala
\.


--
-- Data for Name: guid_nic_photos; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.guid_nic_photos (guid_id, nic_photo_front) FROM stdin;
1	blob:http://localhost:5000/5d4faa0d-07f2-461b-9dc3-094ecc8a9548
\.


--
-- Data for Name: guid_nic_photos_back; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.guid_nic_photos_back (guid_id, nic_photo_back) FROM stdin;
1	blob:http://localhost:5000/39f4afb5-1ae7-4919-ade0-0c4ea06e1fc3
\.


--
-- Data for Name: guid_requests; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.guid_requests (id, status, guid_id, trip_id, user_id) FROM stdin;
\.


--
-- Data for Name: guid_slta_license_photos; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.guid_slta_license_photos (guid_id, slta_license_photo) FROM stdin;
1	blob:http://localhost:5000/e1f6a32d-fea7-4ea9-9e8a-6eb0b95cafb4
\.


--
-- Data for Name: guid_specializations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.guid_specializations (guid_id, specialization) FROM stdin;
1	Wildlife Safari
1	Beach & Water Sports
\.


--
-- Data for Name: guides; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.guides (id, bio, created_at, experience_years, hours_rate, is_available, is_verified, nic_number, slta_license_expiry, slta_license_id, user_id) FROM stdin;
1	Passionate city guide specializing in Colombo’s culture, history, and street food.	2025-10-06 10:48:45.942808	5	25	\N	\N	200301602035	2027-01-07 00:00:00	SL-2045-8752	\N
\.


--
-- Data for Name: hotel_amenities; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.hotel_amenities (hotel_id, amenity) FROM stdin;
1	Free Wi-Fi
1	A/C
1	Spa
1	Pool
1	Restaurant
1	Parking
1	Smoking Area
1	Beach Access
\.


--
-- Data for Name: hotel_images; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.hotel_images (hotel_id, image_url) FROM stdin;
1	blob:http://localhost:5000/a9f3e37d-7b1c-4091-a68c-2c88d14e083f
1	blob:http://localhost:5000/4fb8f31f-cea0-4132-9924-d1f80dad994d
1	blob:http://localhost:5000/7660c2ef-fa20-4740-ad0b-0e8f698d0743
1	blob:http://localhost:5000/21b6c315-1669-41c1-a09d-35562f0af05b
1	blob:http://localhost:5000/abe87c1c-e659-4a8f-9ac0-b0965fcd8b1f
\.


--
-- Data for Name: hotel_license_photos; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.hotel_license_photos (hotel_id, license_photo_url) FROM stdin;
1	blob:http://localhost:5000/e7c8bf30-3ed7-44f8-ab7a-a14b673e718b
\.


--
-- Data for Name: hotels; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.hotels (id, city, created_at, description, district, hotel_name, is_verified, province, registration_no, street, type, user_id) FROM stdin;
1	27	\N	Welcome to Hakmana Ventures Resort, a peaceful getaway nestled in the Southern Province of Sri Lanka. Our resort offers a blend of modern comfort and traditional charm, ideal for both local and international travelers. Enjoy spacious rooms, delicious cuisine, and top-class service with easy access to nearby beaches and cultural attractions.	8	Hakmana Ventures	\N	3	BRN-SL-2022-4587	No. 45, Temple Road	2	\N
\.


--
-- Data for Name: profile_pictures; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.profile_pictures (user_id, profile_picture) FROM stdin;
\.


--
-- Data for Name: room_amenities; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.room_amenities (room_id, amenity) FROM stdin;
\.


--
-- Data for Name: room_images; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.room_images (room_id, image_url) FROM stdin;
\.


--
-- Data for Name: rooms; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.rooms (id, availability, bed_types, created_at, description, max_guests, price_per_night, room_type, hotel_id) FROM stdin;
\.


--
-- Data for Name: trip_interests; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.trip_interests (trip_id, interest) FROM stdin;
\.


--
-- Data for Name: trip_places; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.trip_places (trip_id, place_id) FROM stdin;
\.


--
-- Data for Name: trip_selected_guides; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.trip_selected_guides (trip_id, guide_id) FROM stdin;
\.


--
-- Data for Name: trip_selected_hotels; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.trip_selected_hotels (trip_id, hotel_id) FROM stdin;
\.


--
-- Data for Name: trip_selected_night_hotels; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.trip_selected_night_hotels (trip_id, night_hotel_id) FROM stdin;
\.


--
-- Data for Name: trip_selected_night_rooms; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.trip_selected_night_rooms (trip_id, night_room_id) FROM stdin;
\.


--
-- Data for Name: trip_selected_rooms; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.trip_selected_rooms (trip_id, room_id) FROM stdin;
\.


--
-- Data for Name: trips; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.trips (id, accommodation_preference, activity_level, age_group, agreed_to_terms, base_price, booking_summary_json, budget_range, country, destination, dining_preference, distance_km, duration, email, estimate_duration, full_name, group_type, itinerary, nic_number, number_of_adults, number_of_kids, occupation, optional_contact, phone, pickup_location, referral_source, special_requests, start_time, total_fare, tour_preferences_json, travel_details_json, travel_experience, travel_style, trip_code, trip_end_date, trip_start_date, trip_status, guides, selected_vehicle, selected_vehicle_agency, user_id) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users (id, created_at, doc_id, email, first_name, is_deleted, last_name, role) FROM stdin;
1	2025-10-01 20:46:15.07401	HcNTYyF0YHM8zIzDhUTtnlpy7Np1	sameemadhu2003@gmail.com	\N	\N	\N	traveler
2	2025-10-06 10:40:54.671636	WHNz1x2h0TaocNPkPJKwUXUjIHD2	maduransameera@gmail.com	madhuranga	\N	sameera	partner
52	2025-10-07 20:14:53.558379	r6VOd79a1wW3frNb5nulf1MWbNJ3	hirun08072002@gmail.com	\N	\N	\N	traveler
53	2025-10-07 20:21:22.594382	MfakuI2hqdRlj8OT19WxwLD8cJu1	kawshanmanusha5@gmail.com	Manusha	\N	Kawshan	partner
\.


--
-- Data for Name: vehicle_agencies; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.vehicle_agencies (id, agency_name, city, created_at, description, district, province, registration_no, street, user_id) FROM stdin;
\.


--
-- Data for Name: vehicle_amenities; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.vehicle_amenities (vehicle_id, amenity) FROM stdin;
\.


--
-- Data for Name: vehicle_images; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.vehicle_images (vehicle_id, image_url) FROM stdin;
\.


--
-- Data for Name: vehicles; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.vehicles (id, availability, base_price, capacity, created_at, insurance_expiry_date, insurance_number, is_verified, price_per_kilometer, registration_no, vehicle_model, vehicle_no, vehicle_type, agency_id) FROM stdin;
\.


--
-- Name: comments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.comments_id_seq', 1, false);


--
-- Name: drivers_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.drivers_seq', 1, false);


--
-- Name: guid_requests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.guid_requests_id_seq', 1, false);


--
-- Name: guides_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.guides_seq', 1, true);


--
-- Name: hotels_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.hotels_seq', 1, true);


--
-- Name: rooms_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.rooms_seq', 1, false);


--
-- Name: trips_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.trips_seq', 1, false);


--
-- Name: users_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_seq', 101, true);


--
-- Name: vehicle_agencies_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.vehicle_agencies_seq', 1, false);


--
-- Name: vehicles_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.vehicles_seq', 1, false);


--
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);


--
-- Name: drivers drivers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.drivers
    ADD CONSTRAINT drivers_pkey PRIMARY KEY (id);


--
-- Name: guid_requests guid_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guid_requests
    ADD CONSTRAINT guid_requests_pkey PRIMARY KEY (id);


--
-- Name: guides guides_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guides
    ADD CONSTRAINT guides_pkey PRIMARY KEY (id);


--
-- Name: hotels hotels_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hotels
    ADD CONSTRAINT hotels_pkey PRIMARY KEY (id);


--
-- Name: rooms rooms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT rooms_pkey PRIMARY KEY (id);


--
-- Name: trips trips_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT trips_pkey PRIMARY KEY (id);


--
-- Name: drivers ukojm6yjeacqc5cthc73k5twsnj; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.drivers
    ADD CONSTRAINT ukojm6yjeacqc5cthc73k5twsnj UNIQUE (user_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: vehicle_agencies vehicle_agencies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicle_agencies
    ADD CONSTRAINT vehicle_agencies_pkey PRIMARY KEY (id);


--
-- Name: vehicles vehicles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicles
    ADD CONSTRAINT vehicles_pkey PRIMARY KEY (id);


--
-- Name: trip_selected_night_hotels fk24egauc4mc0jnf1e40hbljji7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_selected_night_hotels
    ADD CONSTRAINT fk24egauc4mc0jnf1e40hbljji7 FOREIGN KEY (trip_id) REFERENCES public.trips(id);


--
-- Name: guid_specializations fk40ru5w1hgyvlo53u0fc10p1j0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guid_specializations
    ADD CONSTRAINT fk40ru5w1hgyvlo53u0fc10p1j0 FOREIGN KEY (guid_id) REFERENCES public.guides(id);


--
-- Name: hotel_license_photos fk5su88evqr2f4oxay4g33x3cup; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hotel_license_photos
    ADD CONSTRAINT fk5su88evqr2f4oxay4g33x3cup FOREIGN KEY (hotel_id) REFERENCES public.hotels(id);


--
-- Name: hotel_amenities fk5v984hm7iyuvyccsgboplo7ii; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hotel_amenities
    ADD CONSTRAINT fk5v984hm7iyuvyccsgboplo7ii FOREIGN KEY (hotel_id) REFERENCES public.hotels(id);


--
-- Name: profile_pictures fk6jju2b9l2tfcam660onl6ecxn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_pictures
    ADD CONSTRAINT fk6jju2b9l2tfcam660onl6ecxn FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: vehicles fk7enq54j7h94472tbm0mwcywre; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicles
    ADD CONSTRAINT fk7enq54j7h94472tbm0mwcywre FOREIGN KEY (agency_id) REFERENCES public.vehicle_agencies(id);


--
-- Name: vehicle_amenities fk7lpeuieuwypqerb5i3ucvmxed; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicle_amenities
    ADD CONSTRAINT fk7lpeuieuwypqerb5i3ucvmxed FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id);


--
-- Name: trip_selected_hotels fk7mrah2rsgygij31nnnhdc8y5s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_selected_hotels
    ADD CONSTRAINT fk7mrah2rsgygij31nnnhdc8y5s FOREIGN KEY (trip_id) REFERENCES public.trips(id);


--
-- Name: trip_selected_hotels fk88xawvh0nkr51vv2fhx5s19up; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_selected_hotels
    ADD CONSTRAINT fk88xawvh0nkr51vv2fhx5s19up FOREIGN KEY (hotel_id) REFERENCES public.hotels(id);


--
-- Name: trips fk8wb14dx6ed0bpp3planbay88u; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT fk8wb14dx6ed0bpp3planbay88u FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: guides fk9epk7rkhp13yrdhou2838dgam; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guides
    ADD CONSTRAINT fk9epk7rkhp13yrdhou2838dgam FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: hotels fkbmtnc1ekbiwke2dfj0p64h4d3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hotels
    ADD CONSTRAINT fkbmtnc1ekbiwke2dfj0p64h4d3 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: trip_selected_night_rooms fkchmuao9t3gcay0y100pgsjly4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_selected_night_rooms
    ADD CONSTRAINT fkchmuao9t3gcay0y100pgsjly4 FOREIGN KEY (trip_id) REFERENCES public.trips(id);


--
-- Name: trips fkdarhcn82pce42w4by5caryevj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT fkdarhcn82pce42w4by5caryevj FOREIGN KEY (guides) REFERENCES public.guides(id);


--
-- Name: drivers fkfscpnjt46gco44xh86l99rxh7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.drivers
    ADD CONSTRAINT fkfscpnjt46gco44xh86l99rxh7 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: trip_interests fkgpdplwil0butd8nsia14nvs5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_interests
    ADD CONSTRAINT fkgpdplwil0butd8nsia14nvs5 FOREIGN KEY (trip_id) REFERENCES public.trips(id);


--
-- Name: trip_selected_rooms fki9fvvmi8stlrr63nw4gnmjots; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_selected_rooms
    ADD CONSTRAINT fki9fvvmi8stlrr63nw4gnmjots FOREIGN KEY (room_id) REFERENCES public.rooms(id);


--
-- Name: guid_languages fkifbmqhcu45ep152lvanx07cci; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guid_languages
    ADD CONSTRAINT fkifbmqhcu45ep152lvanx07cci FOREIGN KEY (guid_id) REFERENCES public.guides(id);


--
-- Name: guid_requests fkite30ddfxh72wvmp8pui2mu6o; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guid_requests
    ADD CONSTRAINT fkite30ddfxh72wvmp8pui2mu6o FOREIGN KEY (trip_id) REFERENCES public.trips(id);


--
-- Name: trips fkkfp2nsqu162nka8q6rng7xgsd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT fkkfp2nsqu162nka8q6rng7xgsd FOREIGN KEY (selected_vehicle) REFERENCES public.vehicles(id);


--
-- Name: drivers fkkg3ke4nsps4oi470e3cig2mps; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.drivers
    ADD CONSTRAINT fkkg3ke4nsps4oi470e3cig2mps FOREIGN KEY (agency_id) REFERENCES public.vehicle_agencies(id);


--
-- Name: guid_requests fkkqd68hp6clij40l91xr4opqo0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guid_requests
    ADD CONSTRAINT fkkqd68hp6clij40l91xr4opqo0 FOREIGN KEY (guid_id) REFERENCES public.guides(id);


--
-- Name: guid_nic_photos_back fkkt79r80kfwbutm61tolwrgybl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guid_nic_photos_back
    ADD CONSTRAINT fkkt79r80kfwbutm61tolwrgybl FOREIGN KEY (guid_id) REFERENCES public.guides(id);


--
-- Name: trip_selected_rooms fkla1j6jbyr81d07kao373tg5t3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_selected_rooms
    ADD CONSTRAINT fkla1j6jbyr81d07kao373tg5t3 FOREIGN KEY (trip_id) REFERENCES public.trips(id);


--
-- Name: guid_requests fkmix4a0n4mcuosumqbgr6ho2sd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guid_requests
    ADD CONSTRAINT fkmix4a0n4mcuosumqbgr6ho2sd FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: guid_nic_photos fkok4485ev1xwcj6cemis7ovcxn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guid_nic_photos
    ADD CONSTRAINT fkok4485ev1xwcj6cemis7ovcxn FOREIGN KEY (guid_id) REFERENCES public.guides(id);


--
-- Name: rooms fkp5lufxy0ghq53ugm93hdc941k; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT fkp5lufxy0ghq53ugm93hdc941k FOREIGN KEY (hotel_id) REFERENCES public.hotels(id);


--
-- Name: vehicle_images fkp6gw8mt61ktmsk5nuc4qid7i8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicle_images
    ADD CONSTRAINT fkp6gw8mt61ktmsk5nuc4qid7i8 FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id);


--
-- Name: agency_license_photos fkpgp1qifxjxpjsf7bf5xyise4d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agency_license_photos
    ADD CONSTRAINT fkpgp1qifxjxpjsf7bf5xyise4d FOREIGN KEY (agency_id) REFERENCES public.vehicle_agencies(id);


--
-- Name: room_amenities fkps6ofup9gxhn8juqvproxbaud; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_amenities
    ADD CONSTRAINT fkps6ofup9gxhn8juqvproxbaud FOREIGN KEY (room_id) REFERENCES public.rooms(id);


--
-- Name: trip_places fkq5s9ydlwtwbfo0so818xdcge8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_places
    ADD CONSTRAINT fkq5s9ydlwtwbfo0so818xdcge8 FOREIGN KEY (trip_id) REFERENCES public.trips(id);


--
-- Name: trip_selected_guides fkqkekdair8ckqeyyxgsxp66ls; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_selected_guides
    ADD CONSTRAINT fkqkekdair8ckqeyyxgsxp66ls FOREIGN KEY (trip_id) REFERENCES public.trips(id);


--
-- Name: hotel_images fkrj3n45f8oqy1yr996g14j757i; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hotel_images
    ADD CONSTRAINT fkrj3n45f8oqy1yr996g14j757i FOREIGN KEY (hotel_id) REFERENCES public.hotels(id);


--
-- Name: guid_slta_license_photos fkt9i5paj5i7v5vts2rmglluu0b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guid_slta_license_photos
    ADD CONSTRAINT fkt9i5paj5i7v5vts2rmglluu0b FOREIGN KEY (guid_id) REFERENCES public.guides(id);


--
-- Name: trips fktge97rv7ogecmh6aam8lnjcyp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT fktge97rv7ogecmh6aam8lnjcyp FOREIGN KEY (selected_vehicle_agency) REFERENCES public.vehicle_agencies(id);


--
-- Name: room_images fktky1jnwoh1hv50m263p2vlt0y; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_images
    ADD CONSTRAINT fktky1jnwoh1hv50m263p2vlt0y FOREIGN KEY (room_id) REFERENCES public.rooms(id);


--
-- PostgreSQL database dump complete
--

